### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/tmp/mmm-tuyasl-token.txt

### ISSUE THREAD

**Issue by Trevotix** [slametps/MMM-TuyaSL#15]
ERROR: Error: ENOENT: no such file or directory, open '/tmp/mmm-tuyasl-token.txt'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2131)
    at Object.readFileSync (node:fs:469:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9462)
    at Class.search (C:\Users\Schueler\MagicMirror\modules\MMM-TuyaSL\node_helper.js:152:21)
    at Class.socketNotificationReceived (C:\Users\Schueler\MagicMirror\modules\MMM-TuyaSL\node_helper.js:246:12)
    at Socket.<anonymous> (C:\Users\Schueler\MagicMirror\js\node_helper.js:104:11)
    at Socket.emit (node:events:513:28)
    at Socket.emitUntyped (C:\Users\Schueler\MagicMirror\node_modules\socket.io\dist\typed-events.js:69:22)
    at C:\Users\Schueler\MagicMirror\node_modules\socket.io\dist\socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by Belladona-c0re** [comment]
did you find the error ?
